
name: Auto Build Changed Qt Projects with MinGW

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-and-build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  

    - name: Install Qt (MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.3'
        arch: 'win64_mingw'

    - name: Add Qt bin directory to PATH
      run: echo "C:\Qt\6.8.3\mingw_64\bin" >> $env:GITHUB_PATH

    - name: Detect changed projects
      id: detect
      run: |
        git fetch origin main
        echo "Changed folders:"
        git diff --name-only origin/main HEAD | cut -d/ -f1 | sort | uniq > changed.txt
        cat changed.txt

    - name: Build changed projects
      run: |
        Get-Content changed.txt | ForEach-Object {
          $project = $_.Trim()
          if ($project) {
            Write-Output "Building $project..."
            $proFile = "$project/$project.pro"
            
            if (Test-Path $proFile) {
              # استخدام المسارات مع علامات الاقتباس للتعامل مع المسافات
              qmake "`"$proFile`""
              mingw32-make
            } else {
              Write-Output "No .pro file in $project, skipping."
            }
          }
        }
