name: CI/CD for Qt qmake Project with MinGW

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt (MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.3'
        arch: 'win64_mingw'

    - name: Add Qt bin directory to PATH
      run: echo "C:\Qt\6.5.0\mingw_64\bin" >> $env:GITHUB_PATH

    - name: Build project using qmake + mingw32-make
      run: |
        qmake test_0.pro
        mingw32-make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          .\*.exe
          .\release\*.exe
          .\debug\*.exe

  release:
    if: github.event_name == 'release'
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.exe
          release/*.exe
