name: Build Packet_Versions/test_0.pro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt (MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.3'
        arch: 'win64_mingw'

    - name: Add Qt bin directory to PATH
      run: echo "C:\Qt\6.8.3\mingw_64\bin" >> $env:GITHUB_PATH

    - name: Build test_0.pro inside Packet_Versions
      run: |
        cd Packet_Versions
        qmake test_0.pro
        mingw32-make

