name: CI for test_0.pro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show directory structure
      run: |
        echo Current Directory: $PWD
        dir Packet_Versions\Packet1 /s

    - name: Install Qt (MinGW)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.3'
        arch: 'win64_mingw'

    - name: Add Qt bin to PATH
      run: echo "C:\Qt\6.8.3\mingw_64\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Build test_0.pro using qmake + mingw32-make
      run: |
        cd Packet_Versions\Packet1\build
        qmake ..\test_0.pro
        mingw32-make

    env:
      Qt6_DIR: C:\Qt\6.8.3\mingw_64
      QT_PLUGIN_PATH: C:\Qt\6.8.3\mingw_64\plugins
      QML2_IMPORT_PATH: C:\Qt\6.8.3\mingw_64\qml
